### PR TITLE
Added cleaned tutorial

### PR DESCRIPTION
**Pull request by mpachiad**

### CODE REVIEW

**Comment by ocefpaf** [comment]
Please let me know when it is ok to merge.

**Comment by mpachiad** [comment]
Yes, please!

Thank you

**Comment by ocefpaf** [comment]
> Yes, please!


Did you mean to close it? If things are not ready you can do a draft PR using GitHub interface. That will tell us to now look at it until you make it final.

**Comment by mpachiad** [comment]
Yes. I apologize for the confusion. I got an error message soon after my request (see below) and I thought my request didn't make it through (newbie in collaborative Github). So I send my file to Nick and he uploaded it. No need to merge any more. 

Thank you so much, Felipe.


Run failed for master (0e81bc8)

Repository: oceanhackweek/ohw20-tutorials
Workflow: pre-commit
Duration: 34.0 seconds
Finished: 2020-08-11 15:08:10 UTC

**Comment by ocefpaf** [comment]
No problem! Let me know if I can help with anything.

**Pull request closed without merging**
