### PR TITLE
Fix the Pangeo binder link and use JupyterLab instead of notebook interface

### PR DESCRIPTION
**Pull request by abkfenris**

### CODE REVIEW

**Comment by ocefpaf** [comment]
I had no idea you were a jupyterlab person. Sorry but we no longer can be friends!

**Comment by abkfenris** [comment]
I may have had an ulterior motive to combine two changes into a single PR.

**Comment by emiliom** [comment]
> I had no idea you were a jupyterlab person. Sorry but we no longer can be friends!

Sorry to barge into this closed PR, but I was saddened to learn that @ocefpaf and I can't be friends either :cry:. But I guess he already knew this about me, so hopefully he accepts me as I am :man_shrugging:

**Comment by ocefpaf** [comment]
Classic notebook forever!!!!!

**Comment by emiliom** [comment]
And I thought I was the old and (relatively) conservative one here :roll_eyes: ...

**Pull request merged**
