### PR TITLE
modify environment.yml to include remotes, sf and rastervis

### PR DESCRIPTION
**Pull request by btupper**
I think this updates the list of R packages to include what we need and to eliminate some redundancies.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks @btupper! Things changed a bit since we last spoke. We have a separate repo for the image due to the hub workflow. I'll merge the files accordingly later today.

**Comment by btupper** [comment]
@ocefpaf does that mean we should discontinue making commits to our fork of ohw20-tutorials for now?  Or do we forge ahead?  We are just on the edge of translating our markdown docs into the Jupyter notebooks.

**Comment by abkfenris** [comment]
@btupper The tutorials will stay here, it's just the environment for JupyterHub that has moved to https://github.com/oceanhackweek/jupyter-image

**Comment by ocefpaf** [comment]
Yes and no. Keep making changes here b/c this is what students will see. Until I figure out a better way I'll just copy the env over to the hub imagine repo.

**Pull request merged**
