### PR TITLE
Install instructions

### PR DESCRIPTION
**Pull request by ocefpaf**
Pinging @mpachiad and @btupper so you can take the install instructions for a test-drive.

### CODE REVIEW

**Comment by btupper** [comment]
Thanks for the installation instructions!  On a relatively new macOS 10.15.5 (Catalina) platform I was able to install the command line version of miniconda (the GUI version installs, but heck if I can find the icon to launch it.). Heads up: the description is for bash, but many relatively newer macOS platforms will be running zsh.  It installed fine running `zsh Miniconda3-latest-MacOSX-x86_64.sh`  Other than needing to install soon-to-be-abandoned Adobe Flash the install was straightforward.  I have successfully launched the Jupyter notebooks.   Just a heads up to @mpachiad (and anyone else needing to know) R v3.6.3 is installed.  So, it looks good to go for macOS!

**Comment by emiliom** [comment]
@ocefpaf I just noticed that you flagged me to review this PR. If you did that 2 days ago, when the PR was submitted, I don't remember getting an email notification. Hmm. Anyway, will do.

For now, after reading the README additions vis a vis installation: The instructions tell users to open `jupyter notebook` .... Ah, again the notebook vs lab philosophical struggle :crossed_swords: . But more seriously, we haven't talked about this more broadly. To minimize confusion, I advocate pointing people primarily/exclusively to Jupyter Lab (ie, for those new or newish to Jupyter, we're helping them set their use patterns going forward) while also making them aware of the notebook-classic interface. I'll try to bring it up on Slack to get input from others. We'll be adding instructions/guidance about conda and Jupyter on the OHW Resources site very soon, so this is part of a broader topic. @leportella will cover Jupyter tomorrow, so let's try to coordinate our "message" and recommendations.

This has potential implications for what jupyter package(s) are included in `environment.yml`.

pinging @leewujung

**Comment by emiliom** [comment]
>  Other than needing to install soon-to-be-abandoned Adobe Flash

@btupper What?! I hope that's not miniconda proper requiring Adobe Flash! Is this unique to macOS 10.15.5? By "GUI" version do you mean the Anaconda installation? If it is Anaconda, maybe we need to strengthen the message that we recommend Miniconda ...

**Comment by ocefpaf** [comment]
Let's do Jupyterlab. The truth is I don't really care. That is jupyter nb b/c I copied and pasted old instructions here.

**Comment by btupper** [comment]
> By "GUI" version do you mean the Anaconda installation? 

Yes - the miniconda install page offers two flavors of the most recent miniconda for macOS.  I tried the GUI version first (that was accidental, I intended to install the shell version which I eventually did so successfully) which did prompt for Flash installation.

**Comment by emiliom** [comment]
> Yes - the miniconda install page offers two flavors of the most recent miniconda for macOS. I tried the GUI version first (that was accidental, I intended to install the shell version which I eventually did so successfully) which did prompt for Flash installation.

Ah. I wasn't aware that the miniconda installation offered a GUI option.

**Comment by ocefpaf** [comment]
> Ah. I wasn't aware that the miniconda installation offered a GUI option.

Me neither! That is new.

**Pull request merged**
